version: '3'

services:
  mongo:
    image: mongo:4.2.5
    container_name: mongodb
    restart: unless-stopped
    ports:
        - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs_api
    container_name: nestjs_api
    restart: unless-stopped
    env_file:
        - .env
    ports:
        - "3000:3000"
    command: bash -c "npm run start:dev"
    volumes:
        - ./src:/app/src
    # depends_on:
    #   - mongo
